parser/main/urls.py
from django.contrib import admin
from django.urls import include, path

from .views import index, parsing

app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('parsing/', parsing, name='parsing'),
]

parser/parser/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

parser/main/models.py
from tabnanny import verbose
from django.db import models

# Create your models here
class Vacancy(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название вакансии')
    address = models.CharField(max_length=200, blank=True, null=True, verbose_name='Адрес')
    employer = models.CharField(max_length=200, verbose_name='Работодатель')
    salary = models.CharField(max_length=200, blank=True, null=True, verbose_name='Зарплата')
    employment = models.CharField(max_length=180, verbose_name='Занятость')
    experience = models.CharField(max_length=180, verbose_name='Опыт работы')
    area = models.CharField(max_length=200, verbose_name='Регион')
    profRole = models.CharField(max_length=200, verbose_name='Специальность')

    def __str__(self) -> str:
        return self.name
    
    class Meta:
        verbose_name = 'Вакансия'
        verbose_name_plural = 'Вакансии'

parser/main/views.py
from crypt import methods
from django.http import Http404
from django.shortcuts import render

from .api_parser import HhParser

from .models import Vacancy

def index(request):
    parser = HhParser()
    areas = parser.getAreas()
    context = {
        'employment': parser.getEmployment(),
        'experience': parser.getExperience(),
        'areas': areas,
        'profRoles': parser.getProfRoles(),
    }
    return render(request, 'main/index.html', context)
    

def parsing(request):
    if request.POST:
        notFound = False
        parser = HhParser()
        params = [request.POST.get('employment'), request.POST.get('experience'), request.POST.get('area'), request.POST.get('profRole')]
        results = parser.parse(params[0], params[1], params[2], params[3])
        if len(results) > 0:
            Vacancy.objects.all().delete()
            for result in results:
                Vacancy.objects.create(name=result[0], address=result[1], employer=result[2], salary=result[3], employment=result[4], experience=result[5], area=result[6], profRole=result[7])
            
            vacancies = Vacancy.objects.all()

            context = {
                'notFound': False,
                'vacancies': vacancies,
                'count': vacancies.count()
            }
        else:
            context = {
                'notFound': True
            }
        return render(request, 'main/result.html', context)
    else:
        vacancies = Vacancy.objects.filter(employer=request.GET.get('order_by').replace('*', ' '))
        context = {
            'current_filter': request.GET.get('order_by'),
            'vacancies': vacancies,
            'count': vacancies.count(),
        }
        return render(request, 'main/result.html', context)
    

parser/main/templates/main/index.html
<h1>Выберите параметры запроса</h1>


<form action="parsing/" method="post">
    {% csrf_token %}
{% if experience %}
<select name="experience" id="experience-select">
    {% for key, value in experience.items %}
    <option value={{ key }}>{{ value }}</option>
    {% endfor %}
</select>
{% endif %}

{% if employment %}
<select name="employment" id="employment-select">
    {% for key, value in employment.items %}
    <option value={{ key }}>{{ value }}</option>
    {% endfor %}
</select>
{% endif %}

{% if areas %}
<select name="area" id="area-select">
    {% for el in areas %}
    <option value={{ el.2 }}>{{ el.3 }}, {{ el.1 }}</option>
    {% endfor %}
</select>
{% endif %}

{% if profRoles %}
<select name="profRole" id="profRole-select">
    {% for key, value in profRoles.items %}
    <option value={{ key }}>{{ value }}</option>
    {% endfor %}
</select>
{% endif %}
<button type="submit">Получить аналитику</button>
</form>

{% if params %}
    <h3>Запросы по параметрам</h3>
    {% for param in params %}
    <p>{{ param }}</p>
    {% endfor %}
{% endif %}

{% if result %}
    {% for el in result %}    
    <p>{{ result }}</p>
    {% endfor %}
{% endif %}

parser/main/templates/main/result.html
{% load main_tags %}

<h1>Результат запроса</h1>
{% if notFound %}
<h2>Вакансии по данному запросу не найдены</h2>
{% endif %}

<a href="{% url "main:index" %}">Новый запрос</a>
{% if count %}
    <h2>Всего найдено вакансий: {{ count }}</h2>
{% endif %}

{% company_names as companies %}

{% if companies %}
<h3>Фильтр по компаниям</h3>
<form action="", method="get">
<select name="order_by", >
{% for company in companies %}
<option value={{ company }} {% if company == current_filter %} selected="selected"{% endif %} >{% clear_name company %}</option>
{% endfor %}
</select>
<button type="submit">Применить</button>
</form>
{% endif %}

{% if vacancies %}
    <table>
        <thead>
            <tr>
                <th>Название вакансии</th>
                <th>Адрес</th>
                <th>Работодатель</th>
                <th>Зарплата</th>
                <th>Занятость</th>
                <th>Опыт работы</th>
                <th>Регион</th>
                <th>Специальность</th>
            </tr>
        </thead>
        <tbody>
    {% for vacancy in vacancies %}
            <tr>
                <th>{{ vacancy.name }}</th>
                <th>{{ vacancy.address }}</th>
                <th>{{ vacancy.employer }}</th>
                <th>{{ vacancy.salary }}</th>
                <th>{{ vacancy.employment }}</th>
                <th>{{ vacancy.experience }}</th>
                <th>{{ vacancy.area }}</th>
                <th>{{ vacancy.profRole }}</th>
            </tr>
    {% endfor %}
        </tbody>   
    </table>
{% endif %}

<style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }

    a {
        margin 10px;
    }
    </style>